baseURL = "http://godler.art/"
languageCode = "de-at"
title = "Katharina Godler"
theme = "hello-friend-ng"

[author]
    name = "Katharina Godler"

[params]
    # Subtitle for home
    homeSubtitle = "Autorin und Journalistin"

    backgroundImage = "home/RauchenwaldWebseite-Startseite.jpg"

    # Enable sharing buttons, if you linke
    enableSharingButtons = true

    defaultTheme = "light"

    footerLeft = "<a href=\"mailto:katharina@godler.art\">katharina@godler.art</a>"
    footerRight = " "

  [params.logo]
    logoText = "Katharina Godler"
    logoMark = " "
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    logoCursorDisabled = true

[[params.social]]
    name = "facebook"
    url = "https://www.facebook.com/katharina.godler/"

#[[params.social]]
#    name = "instagram"
#    url = "https://www.instagram.com/kraeheedeltraud/"

[[params.social]]
    name = "twitter"
    url = "https://twitter.com/EdeltraudKrahe"


[languages]
    [languages.en]
        title = "Katharina Godler"

[menu]
  [[menu.main]]
    identifier = "radio"
    name       = "Radio"
    url        = "radio/"
    weight     = 1

  [[menu.main]]
    identifier = "belletristik"
    name       = "Belletristik"
    url        = "belletristik/"
    weight     = 2

  [[menu.main]]
    identifier = "lyrik"
    name       = "Lyrik"
    url        = "lyrik/"
    weight     = 3

  [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "about/"
    weight     = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true